spring:
  application:
    name: catbox

  # Docker Compose Profile
  docker:
    compose:
      enabled: false
      file: compose.yaml

  # Default datasource (H2) - Inherited from application.yml
  # Default JPA (H2) - Inherited from application.yml
  # Default H2 Console - Inherited from application.yml

  # VIRTUAL THREADS (Java 21+)
  # This is inherited from application.yml (enabled: true)
  # We MUST ensure it is not disabled by a profile.
  threads:
    virtual:
      enabled: true

  # KAFKA CONFIGURATION
  # All Kafka config (clusters, routing, factory)
  # is inherited from application.yml.
  # We MUST NOT define a default spring.kafka.bootstrap-servers
  # here, as it conflicts with the dynamic cluster map.

server:
  port: 8080

# Logging is inherited from application.yml

---
# Azure SQL Profile (when using docker-compose)
spring:
  config:
    activate:
      on-profile: azuresql

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=catbox;encrypt=true;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: YourStrong@Passw0rd

  jpa:
    hibernate:
      ddl-auto: update # Use 'update' for persistent DB
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true

  h2:
    console:
      enabled: false # Disable H2 console when using SQL Server
