spring:
  application:
    name: catbox

  # Docker Compose Profile - Azure SQL Edge and Kafka
  docker:
    compose:
      # Set to true to enable Spring Boot's automatic Docker Compose lifecycle management
      # When enabled, Spring Boot will start/stop the services defined in compose.yaml
      enabled: false
      file: compose.yaml

  # Default datasource (H2) - Override when using Azure SQL with docker-compose
  datasource:
    url: jdbc:h2:mem:catboxdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  threads:
    virtual:
      enabled: false  # Set to true when using Java 21+

  # Kafka configuration
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
    consumer:
      group-id: catbox-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8080

logging:
  level:
    com.example.catbox: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

---
# Azure SQL Profile (when using docker-compose)
spring:
  config:
    activate:
      on-profile: azuresql

  datasource:
    url: jdbc:sqlserver://localhost:1433;database=catbox;encrypt=true;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: YourStrong@Passw0rd

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true

  h2:
    console:
      enabled: false
