apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: traceID
          matcherRegex: '"trace.id":"([a-f0-9\-]+)"'
          # Example: point to Tempo if added later; keep disabled unless Tempo is present
          url: ''
          urlDisplayLabel: 'Trace'
